Name:           ros-indigo-airbus-coop
Version:        0.0.3
Release:        0%{?dist}
Summary:        ROS airbus_coop package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://ros.org/wiki/airbus_coop
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-airbus-cobot-gui
Requires:       ros-indigo-airbus-docgen
Requires:       ros-indigo-airbus-plugin-log-manager
Requires:       ros-indigo-airbus-plugin-node-manager
Requires:       ros-indigo-airbus-plugin-rqt
Requires:       ros-indigo-airbus-plugin-rviz
Requires:       ros-indigo-airbus-pyqt-extend
Requires:       ros-indigo-airbus-ssm-core
Requires:       ros-indigo-airbus-ssm-plugin
Requires:       ros-indigo-airbus-ssm-tutorial
BuildRequires:  ros-indigo-catkin

%description
The airbus_coop metapackage

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Sep 06 2017 Nadia Hammoudeh Garcia <nhg@ipa.fhg.de> - 0.0.3-0
- Autogenerated by Bloom

